### PR TITLE
Fixed Scaling issue for OpenEBS logo on documentation site

### PR DESCRIPTION
**Pull request by brute4s99**
Signed-off-by: brute4s99 [LAPTOP] <piyushaggarwal002@gmail.com>

I used the idea suggested in [issue #323](https://github.com/openebs/openebs-docs/issues/323)

### CODE REVIEW

**Comment by Akash4927** [comment]
Hi @brute4s99, thanks for the PR.
Can you please post the screenshots?

**Comment by brute4s99** [comment]
Please see this, @Akash4927 
image

**Comment by brute4s99** [comment]
Previously it used to show like this
image

**Comment by Akash4927** [comment]
It looks good.
Can you please post the screenshots in mobile view also?

**Comment by brute4s99** [comment]
sure, just a sec

**Comment by brute4s99** [comment]
Here you go..
image

**Comment by brute4s99** [comment]
if you can help me fix that overlapping issue for dropdown menu(v0.7) , would be great! 
@Akash4927

**Comment by Akash4927** [comment]
Sure @brute4s99, sure I'll help you with that.

**Comment by brute4s99** [comment]
should I reopen an ngrok link for you to inspect, @Akash4927 ?

**Comment by Akash4927** [comment]
Hi @brute4s99 
```diff
diff --git a/website/static/css/custom.css b/website/static/css/custom.css
index d293193a..9d3fc43c 100644
--- a/website/static/css/custom.css
+++ b/website/static/css/custom.css
@@ -101,12 +101,12 @@ footer .sitemap .nav-home {
 /* NAV bar */
 
 .fixedHeaderContainer header img#logo {
-    height: 100%;
-    margin-right: 10px;
+    height: 60%;
+    margin-right: 5px;
 }
 .fixedHeaderContainer header img {
     height: 60%;
-    margin-right: 10px;
+    margin-right: 5px;
 }
 
 .fixedHeaderContainer header h2 {
@@ -205,6 +205,9 @@ pre code {
         width: 108px;
         height: auto;
     }
+    .fixedHeaderContainer header img#logo {
+        width: 20px;
+    }
     .fixedHeaderContainer header h2{
         color: #fff;
     }
@@ -217,6 +220,9 @@ pre code {
         width: 141px;
         height: auto;
     }
+    .fixedHeaderContainer header img#logo {
+        width: 30px;
+    }
     .fixedHeaderContainer header h2{
         color: #fff;
     }
```

I hope adding this will work.
Please give it a try.

**Comment by brute4s99** [comment]
okay, @Akash4927 . Hang on

**Comment by Akash4927** [comment]
@brute4s99 You need to sign the second commit too.
Do something like:- 
`git commit -s --amend` & `git push origin staging`

**Comment by brute4s99** [comment]
@Akash4927 I apologize but I'll have to take a short break, brb in an hour or so
Till what time can you help me with this today?

**Comment by Akash4927** [comment]
@brute4s99 Do you need help in DCO check?

**Comment by brute4s99** [comment]
Hey @Akash4927 ! I made the changes.

Please refer the screenshot attached -
image

**Comment by brute4s99** [comment]
> @brute4s99 Do you need help in DCO check?

Thanks, but I just had problems rebasing, had some wrong cmmits pushed to fork.
All fixed in latest commit! :confetti_ball:

**Comment by visualapps** [comment]
hi @Astha2111 can u please review OpenEBS Docs logo here. Do we want to use mule with text version of logo here or just text version.

**Comment by brute4s99** [comment]
Please review this revision, @visualapps 
image

**Comment by brute4s99** [comment]
>  @brute4s99 you can reduce the image size for smaller viewport 

I'm sorry, @visualapps but I don't know how to do that. Any help would be appreciated!

**Comment by visualapps** [comment]
@brute4s99 lgtm. thanks

**Pull request merged**
