### PR TITLE
Jira docs

### PR DESCRIPTION
**Pull request by DoriftoShoes**
Adding jira deployment

### CODE REVIEW

**Comment by ranjithwingrider** [comment]
@DoriftoShoes So we need to map this id of the page to website.json file to see in UI. Where we will include this one? Under Stateful Applications?

**Comment by DoriftoShoes** [comment]
> @DoriftoShoes So we need to map this id of the page to website.json file to see in UI. Where we will include this one? Under Stateful Applications?

Yeah, under stateful applications.  Let me push an update that includes that.

**Comment by umamukkara** [comment]
Once the .json file is updated, please merge it.

**Comment by DoriftoShoes** [comment]
I must be crazy.  Can someone point me to where I find the website.json file?

**Comment by ranjithwingrider** [comment]
@DoriftoShoes sorry. there was some confusion from my side reg file name . it is sidebars.json under website folder. Anyway I will do it Patrick. I will merge this one to staging and include it in corresponding in website.json.

**Comment by DoriftoShoes** [comment]
Thanks!

**Pull request merged**
