### PR TITLE
Fixed some grammar errors in ibmcloud.md

### LINKED ISSUE #378: Some Typo in openebs-docs/docs/ibmcloud.md
There some punctuation spacing mistakes

### PR DESCRIPTION
**Pull request by LiTO773**
Fixes #378 

Signed-off-by: Luis Pinto devluisp@hotmail.com

### CODE REVIEW

**Comment by LiTO773** [comment]
Signed-off-by: Luis Pinto devluisp@hotmail.com

**Comment by Akash4927** [comment]
@LiTO773 please sign your commit. PTAL at https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by LiTO773** [comment]
@mahebbar Do you know why my Signed-off-by isn't working? I agree with the DCO, but everytime I amend the commit it doesn't accept :/

**Comment by LiTO773** [comment]
@Akash4927 sorry to bother you too, but do you know why my Signed-off-by isn't working? I'm amending my commits to include `Signed-off-by: Luis Pinto <devluisp@hotmail.com>`, but it still doesn't work. I've read the DCO and agree with it btw.

**Comment by Akash4927** [comment]
@LiTO773 I see you have 3 commits and 1 of the commit has two different signs. Please fix them.

**Comment by LiTO773** [comment]
@Akash4927 Fixed :), sorry for the trouble.

**Pull request merged**
