### PR TITLE
Changes in Left Sidebar UI

### LINKED ISSUE #322: UX / JavaScript - More elegant LHS menu for docs.openebs.io
Issue type: Feature enhancement
Complexity: Easy
Issue description:
OpenEBS docs site https://docs.openebs.io/ has two menus - Main menu on the LHS and TOC menu on the RHS.

The background color for LHS is white and could look better like shown in the below link.
https://console.bluemix.net/docs/containers/cs_storage_basics.html#kube_concepts

### PR DESCRIPTION
**Pull request by arshadkazmi42**
- Sidebar made full height
- Background color changed
- Added padding to child elements.

Closes #322

### CODE REVIEW

**Comment by Akash4927** [comment]
Hi, @arshadkazmi42, Thanks for the PR.
It looks awesome, just a small set of changes required. 

The sidebar is not scrollable anymore as well as the search bar has moved slightly right.

screenshot from 2018-10-05 22-16-16

**Comment by arshadkazmi42** [comment]
@Akash4927 Thank you for the review. working on the changes.

**Comment by arshadkazmi42** [comment]
@Akash4927 done with the changes 👍

**Comment by Akash4927** [comment]
Thanks for addressing the comments.

**Comment by arshadkazmi42** [comment]
@sagarkrsd 

**MacOS - Firefox**
macos_firefox

**MacOs - Chrome**
macos_chrome

These are the snapshots after the change.

> also the background colour
what is the background color change needed?

**Comment by sagarkrsd** [comment]
@arshadkazmi42 Thanks for posting the screenshot !
The change related to sidebar is for the background colour highlighting length and not the colour itself that comes into effect when we select a particular sidebar menu like **Introduction** in your latest screenshot, the colour is good but the length of the highlighted part looks going out of the box.

**Comment by arshadkazmi42** [comment]
Just checking if I got it right, the introduction selected color starting should align with the parent title start?

**Comment by sagarkrsd** [comment]
Right @arshadkazmi42  and also the end should be just inside the larger box end line not exactly the same.

**Comment by arshadkazmi42** [comment]
@sagarkrsd 
how about this type of color

screen shot 2018-10-09 at 7 04 20 pm

**Comment by sagarkrsd** [comment]
@arshadkazmi42 The padding is good but you can keep the previous colour only.

**Comment by arshadkazmi42** [comment]
@sagarkrsd Is this fine?

screen shot 2018-10-10 at 10 36 50 am

**Comment by sagarkrsd** [comment]
Yes @arshadkazmi42 , its good !
Thanks for your patience and changes made !

**Comment by arshadkazmi42** [comment]
cool. let me just update the PR right away

**Comment by arshadkazmi42** [comment]
@sagarkrsd updated the PR

**Pull request merged**
