### PR TITLE
Signed-off-by: Utkarsh <um9519@gmail.com>

### PR DESCRIPTION
**Pull request by ulshell**
Correcting Typo in ibmcloud.md
Issue #378

### CODE REVIEW

**Comment by ulshell** [comment]
Kindly review it @Akash4927

**Comment by ulshell** [comment]
Kindly check for it

**Comment by Akash4927** [comment]
@ulshell Please change your commit message and put your sign in description instead of heading.

**Comment by Akash4927** [comment]
This is fixed using https://github.com/openebs/openebs-docs/pull/385

**Comment by ulshell** [comment]
Thank you, but I have done that before

**Comment by ulshell** [comment]
Hello @Akash4927 Will I will Be getting openebs hacktoberfest t-shirt or not

**Pull request closed without merging**
