### PR TITLE
Fixed typos in installation.md

### PR DESCRIPTION
**Pull request by swetax**
Signed-off-by: Sweta Behera <sweta.saena@gmail.com>

### CODE REVIEW

**Comment by Akash4927** [comment]
Hi @swetax, please resolve conflicts.

**Comment by swetax** [comment]
Hi @Akash4927 . Can you please tell me which conflicts I should resolve? I am unable to understand.

**Comment by Akash4927** [comment]
Hi @swetax, conflicts are in `docs/installation.md` file. 
Line 54, 62, 77 & 98

**Comment by swetax** [comment]
@Akash4927  I resolved the conflicts. Please review it.

**Pull request merged**
