### PR TITLE
fix spacing

### PR DESCRIPTION
**Pull request by StrikerRUS**
<details>
<summary>DCO</summary>

Signed-off-by: StrikerRUS < nekit94-12 at hotmail.com >
</details>

### CODE REVIEW

**Comment by Akash4927** [comment]
@StrikerRUS Please fix the DCO. 
It is expecting `Nikita Titov <nekit94-12@hotmail.com>`

Please have a look at it.
https://github.com/openebs/maya/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by StrikerRUS** [comment]
@Akash4927 Thank you! Fixed.

**Comment by StrikerRUS** [comment]
@Akash4927 All tests are green now. Should anything else be done?

**Comment by Akash4927** [comment]
@StrikerRUS Thanks for the change.

**Pull request merged**
