### PR TITLE
Maintain docs version using JSON file

### LINKED ISSUE #313: Maintain docs version using json file
Currently, the version is hardcoded in the docusaurus code. Whenever we release a new version, we need to add it in the code. 
https://github.com/openebs/openebs-docs/blob/80566bf9b4a00bd8ed2cde21fffce9b82c7ec48c/website/node_modules/docusaurus/lib/core/nav/HeaderNav.js#L242

Instead of this, we need to maintain a `version.json` file which will have all the versions and their links. (Similar to [sidebars.json](https://github.com/openebs/openebs-docs/blob/master/website/sidebars.json) file)

Implement logic to fetch version from version.json file and show in the dropdown menu.

Whenever we release a new version, we need to update the `version.json` file.

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #313 
@Akash4927 Please take a look, is it the right way to implement it? I've made a function in `HeaderNav` component which fetches the latest version from `versions.json` and I called it wherever needed...

### CODE REVIEW

**Comment by Akash4927** [comment]
Thanks for the PR @Rishabh570 
One thing we need to maintain a number of versions and their links.
Structure of versions.json file should be something like:-

```
{
     versions: {
         0.7: "docs.openebs.io",
         0.6: "v06-docs.openebs.io",
         0.5: "v05-docs.openebs.io"
     }
}
```

you can look at the implementation of sidebars.json for the same.

**Comment by Rishabh570** [comment]
So, do we need to place the links where `v0.7` is written currently (in headerNav.js)?
Thanks for review!

**Comment by Rishabh570** [comment]
@Akash4927 I've updated `versions.json` and `headerNav.js` also. Now links to docs are fetched from versions.json file...
Please take a look :)

**Comment by Akash4927** [comment]
@Rishabh570 If I add a new version tomorrow, then I have to update the versions.json file as well as the code.
We only want to update the versions.json file and it should reflect on the version drop-down.

**Comment by Rishabh570** [comment]
@Akash4927 Sorry, I was a little confused. Please take a look now :)

**Comment by Rishabh570** [comment]
@Akash4927 Please take a look...I've updated my PR

**Comment by Rishabh570** [comment]
@Akash4927 Here is the screenshot of localhost, PTAL

screenshot from 2018-10-22 17-09-58

**Comment by Akash4927** [comment]
Hi @Rishabh570, thanks for the change, but the issue is still the same.
Let us consider a scenario where we release a new version of OpenEBS and we update the docs accordingly.
In that case, I have to change the code as well as the JSON file to make it work.
We want something where you just need to update the JSON file, not the code.

**Comment by Rishabh570** [comment]
@Akash4927 Okay, so the indexes through which I'm accessing the values are the issue, right? as they'll change...

**Comment by Rishabh570** [comment]
@Akash4927 Okay, so now I'm accessing the latest version by using the `latest` key, so now if we update the docs i.e., place new version number and new URL (related to that version) in that key-value pair, we won't need to change anything in the code...but older versions will be accessed by their version number only as we can't access them like old, older, oldest....keys from JSON. Please correct me if I'm wrong here (again) :)

PS: Sorry, I'm taking your too much time...

**Pull request merged**
