### PR TITLE
Bolded key details in on `blockDeviceList` options

### PR DESCRIPTION
**Pull request by ryanrolds**

### CODE REVIEW

**Comment by ranjithwingrider** [comment]
Can you please complete the DCO also?

**Comment by ranjithwingrider** [comment]
@ryanrolds  Can you complete the DCO issue?

**Comment by ryanrolds** [comment]
I've tried multiple time to resolve the build error, as you can see with the commit history. I don't know what the issue is or what the purpose of the DCO is, but it seems like an impediment to contributing.

**Comment by ryanrolds** [comment]
The commit it very basic changes. Maybe someone more familiar with idiosyncrasies of the build process can make them instead.

**Comment by ranjithwingrider** [comment]
@ryanrolds You have to commit the PR using below one:

Signed-off-by: github.user.name <user.email>

**Comment by kmova** [comment]
Thanks for input @ryanrolds. Will try to update contributing guide.

To close this can you provide a email id to be associated with commit.

I use the following to sign my commits.
`git commit -s ...` signs the commits.

**Comment by ryanrolds** [comment]
Please see the commit message of the last comment it ends with `Signed-off-by: Ryan Olds <ryanrolds@gmail.com>`.

**Comment by kmova** [comment]
@ryanrolds - apologies for missing that one. Also I see how frustrating it can be when a small change like this can't get in immediately into docs.

**Pull request closed without merging**
