### PR TITLE
Corrected shebang line. Added missing exclamation mark. Signed-off-by…

### PR DESCRIPTION
**Pull request by divygarg**
…: Divy Garg <divygarg95@gmail.com>

Corrected shebang line. Added missing exclamation mark. 

Signed-off-by: Divy Garg <divygarg95@gmail.com>

### CODE REVIEW

**Comment by divygarg** [comment]
Review it!

**Comment by divygarg** [comment]
Can you review this please!

**Comment by Akash4927** [comment]
@divygarg The file you changed is not in use anymore. We'll be removibg this file soon. Due to this I am closing your pull request.

**Comment by divygarg** [comment]
:(

**Pull request closed without merging**
