### PR TITLE
Fix expanding and compressing of headers in side navbar

### LINKED ISSUE #320: Expanding  one heading should compress the other expanded heading
Issue type: Feature enhancement
Complexity: Easy
Issue description: 
OpenEBS docs site https://docs.openebs.io/ has two menus  - Main menu on the LHS and TOC menu on the RHS.

On the LHS if you click the Red heading "Concepts" the section expands, but the already expanded section "Getting Started" does not compress. We would like to have this fixed.

### PR DESCRIPTION
**Pull request by agarwalrounak**
Fixes #320 
Now, on clicking a section, the already expanded section collapses. Also, on reloading the page, the relevant section is expanded.

**Before**:
old (1)

**After**:
new

Signed-off-by: Rounak Agarwal <rounakr.ag73@gmail.com>

### CODE REVIEW

**Comment by agarwalrounak** [comment]
@umamukkara @AmitKumarDas Please review.

@aditya109 I was able to resolve the problem that I was talking about. Now, it works fine.

**Comment by ranjithwingrider** [comment]
Looks good with respect to functionality.
@sagarkrsd @qiell Can you help to check the code changs once?

**Comment by agarwalrounak** [comment]
I have rebased my PR. Please review.

**Comment by sagarkrsd** [comment]
@agarwalrounak Can you please remove first two files from the commit i.e. metadata.js and en.json, those are not required.

**Comment by sagarkrsd** [comment]
BTW thank you so much for the changes @agarwalrounak :tada: :+1:

**Comment by agarwalrounak** [comment]
Hi Sagar! I have made the necessary changes.

**Pull request merged**
