### PR TITLE
Fixing security issues due to some node packages

### PR DESCRIPTION
**Pull request by sonapraneeth-a**
Some security vulnerabilities are shown in the repo web-page when using current node modules. Checking if upgrading packages fixes the security vulnerabilities in node packages.

Signed-off-by: Sona Praneeth Akula <sonapraneeth.akula@gmail.com>

### CODE REVIEW

**Comment by sonapraneeth-a** [comment]
Also, I was wondering what is the need for ```node_modules``` directory in website as it can be 
re-generated from ```package.json```?

**Comment by ranjithwingrider** [comment]
cc @sagarkrsd

**Comment by kmova** [comment]
Hi @sonapraneeth-a -- would you like to continue working on this PR? 

cc: @sagarkrsd - do you have any suggestions on how to proceed with this PR?

**Comment by sagarkrsd** [comment]
Thank you @kmova.
@sonapraneeth-a I see this PR consists of two things, one is typo fixes and other is vulnerability fixes.
Regarding vulnerability fixes, have you tested all the basic functionalities locally after the docusaurus version upgrade?
Can you post a screenshot of the docs home page after this change?

**Pull request closed without merging**
