### PR TITLE
[WIP]Added CRDs that have to be deleted manually

### PR DESCRIPTION
**Pull request by anupriya0703**
Signed-off-by: anupriya0703 <anupriya.gupta@mayadata.io>

### CODE REVIEW

**Comment by ranjithwingrider** [comment]
@anupriya0703 Thanks for the changes. I have deployed 1.11 along with CSPC and CSI operators... So I have seen some of the CRDs need to added and some of the CRDs are not present in the latest version.. Details are follows.

### Need to add
```
1. csidrivers.csi.storage.k8s.io
2. csinodeinfos.csi.storage.k8s.io
3. volumesnapshotclasses.snapshot.storage.k8s.io
4. volumesnapshotcontents.snapshot.storage.k8s.io
5. volumesnapshots.snapshot.storage.k8s.io
```
### Need to remove the following CRDs
```
1. disks.openebs.io
2. cstorpoolclusters.openebs.io
```

**Comment by akhilerm** [comment]
The below CRDs also need to be removed while uninstalling
```
blockdevices.openebs.io
blockdeviceclaims.openebs.io
```

Disk CRD will be automatically deleted if present by  NDM 0.6 (OpenEBS 1.11). No need to remove disk CRD.
So not required to delete `disks.openebs.io`

**Comment by ranjithwingrider** [comment]
@akhilerm Its already present in our uninstall section. Now, we are adding the latest CRDs which are part of the latest release... 
image

Yes regarding the disk card, I have mentioned in the above comment to remove disk CRDs from existing doc since it is not getting installed during the 1.11 installation.

Thank you @akhilerm  for looking into it...

**Comment by prateekpandey14** [comment]
@ranjithwingrider below CRDs are no longer exists( deprecated) ( but there are chances that people can have these CRDs as well)

```
  kubectl delete crd cstorpoolclusters.openebs.io
  kubectl delete crd cstorvolumeclaims.openebs.io
  kubectl delete crd cstorvolumereplicas.openebs.io
```

**Comment by ranjithwingrider** [comment]
@prateekpandey14 ok. Out of the 3, I can see `cstorpoolclusters.openebs.io` was not installed with latest 1.11 version. But remaining 2 are present.

**Comment by akhilerm** [comment]
> Yes regarding the disk crds, I have mentioned in the above comment to remove disk CRDs from existing doc since it is not getting installed during the 1.11 installation.

In 1.11, we also make sure to delete disk CRD if it exists. eg: in case of upgraded setups disks may still be present. we automatically delete the disk CRDs in those cases.

**Pull request closed without merging**
